apiVersion: v1
kind: ServiceAccount
metadata:
  name: bastion
---
apiVersion: v1
kind: Pod
metadata:
  name: bastion
  annotations:
    consul.hashicorp.com/connect-inject: "true"
  labels:
    app: bastion
spec:
  serviceAccountName: bastion
  containers:
  - name: bastion
    image: nginx:stable
    imagePullPolicy: IfNotPresent
